export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_ARTICLE_DATA: 'SET_ARTICLE_DATA',
	RESET_ARTICLE_DATA: 'RESET_ARTICLE_DATA',
	ADD_COMMENT: 'ADD_COMMENT',
	REMOVE_COMMENT: 'REMOVE_COMMENT',
};
